---
#
# This file contains settings for the Lambda function
#

# This is the maximum amount of time that the Lambda function will
# run.  The function should normally run within 1 second or less,
# but service outages/issues may cause exponential back-off and
# increased wait times, so don't set this too low.
#
# NB: You are only billed for what you use.
lambda_timeout_in_seconds: 60

